### PR TITLE
Rebase

### PR DESCRIPTION
**Pull request by thelamer**
Part of a larger rebase effort to get all of our GUI images in sync with the new desktop base.

### CODE REVIEW

**Comment by AlmightyFrog** [comment]
Hi, did anyone else yet try the new image?
Strangely it looks like docker.io/lsiodev/digikam:amd64-2023-03-17-pkg-c339734b-dev-9a2be46bd4816f46a60d125ccef11ec463f4faca is indeed a x86 image.

Anyhow, i fear the change! Yesterday i already tinkered around with KasmVNC in context of linuxserver/chromium and an attempt to bundle cura within it.
Today i tried the new build triggered by this PR and i am frightened that this will totally kill linuxserver/digikam (for me at least):
- having rdp was nice so far, as you could use native clients (windows rdp and linux remmina) to bet a low latency high video quality access) besides posibility to use webbrowser (which i rarely used since rdp performance improved a year ago or so)
- surfing/watching youtube in linuxserver/chromium was working good so far - there was a noticable input lag and FPS didn't go above 30 fps but for consuming media it was fine. audio was a little laggy, but playing a video was even a little better than the current rdp experience!
- what was bad was the overall display quality, not sure if i want to look through my high res pictures on a full hd or even 4k monitor. don't get me wrong, as browser in browser experience was really good, but this digikam has different priorities
- i couldn't get on the windows 11 machine get KasmVNC running in firefox, i just gave up and used edge. on my linux computer there was no issue.
- even scrolling through pictures was glitchy and not a good experience. i didn't manage to reliably click/scroll through my photos and gave up; after switching back to old image everything works again properly.

i really hope, someone will look at this image and try to use it before migrating from rdesktop base to kasmvnc.

what is the plan, will there be some versions in parallel or hard cut? is there a possibility to add to base image support for rdp?

**Comment by thelamer** [comment]
@AlmightyFrog please review the documentation here: 
https://github.com/linuxserver/docker-baseimage-kasmvnc

There is even a true 24 bit RGB lossless mode. Try using https port 3001 and lossless or the extreme preset. I find it very hard to believe that you are seeing a fidelity regression given I have worked full time for over a year hyper focused on this particular issue. 

When it comes to using Firefox that is up to you, but I would always recommend a chromium based browser (so many options) clientside as the javascript and webassembly engine is many times faster. 

Please open the sidebar and play with the settings, by default you would be using webp and medium preset which is optimized for bandwidth, but with the new image you have granular control over what you want. 

Here is a quick comparison of a fullscreen 1440P youtube vid in xrdp and kasmvnc: 

kasmvnc: https://files.catbox.moe/xfsa79.mp4
webtop: https://files.catbox.moe/7zryyx.mp4

I can understand you like your setup the way it is but RDP with a native client is gonna be gone soon, but these images will still be maintained https://github.com/linuxserver/docker-rdesktop you can always install digikam on them to continue using an RDP client.

**Review by thespad — APPROVED** [review]

**Comment by AlmightyFrog** [comment]
@thelamer 
thanks for your effort!
I've already tried using different modes; it seems like when i am using firefox it really is a little worse than chromium.
Anyhow, still the pure RDP works better for me.

Using current container (Guacamole/NoVNC?) is similar performant like KasmVNC, besides there it performs similar in both firefox and chromium.
Anyhow, i guess that is a problem on my side.

You're right, maybe it is time to say goodbye to official docker-digikam for people who did want to use the RDP. It is a little sad, but that's life cause it was cool to have both RDP for general use and HTTP client for fallback.
But as docker-rdesktop will be maintained further, i'll then just jump to that and add an derived Dockerfile installing digikam.

**Comment by thelamer** [comment]
Given the nature of this program (and this is just my personal opinion) I would think the lossless mode would be invaluable for gamut adjustments etc. It is high bandwidth but it is actually lossless, and RDP lossless mode is actually compressed (though that is not posted officially anywhere) plus linux xrdp does not support the fancy magic for graphics primatives that native windows servers do. 
In the end though port 3389 was never advertised on any of these GUI containers as it was more a side effect of the technology stack used to present the application to a web browser than it was an intended feature. The goal was always to turn a desktop application into a web application. 
As far as any latency you are feeling on input that stuff will gradually improve as time goes on and the KasmVNC base continues to receive updates. 
For example right now three frames (50 ms of baked in latency) is used as a buffer pool to do essentially a vsync client-side in the browser to prevent tearing. In the future there will be more knobs to turn that off and get instant rect rendering when the client receives it. 
I am more making this post as a general statement to any user than lands on this from google, we know people do not like it when stuff in their already working setup is ripped out from under them, but these images must move forward to provide the best web native experience possible.

**Pull request merged**
