### PR TITLE
rebase to debian bookworm and ingest official appimage

### PR DESCRIPTION
**Pull request by thelamer**
Arch head package is currently not working inside Docker, this swaps to Debian for x86_64 and leaves the aarch64 image in place to see if it gets fixed. 
Ingests the official appimage from the MIT mirror and swaps firefox to chromium.

### CODE REVIEW

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
One issue is, because the external trigger will now be based on appimage releases, the aarch64 build may keep failing due to not being in sync with the arch baseimage

**Comment by thelamer** [comment]
> One issue is, because the external trigger will now be based on appimage releases, the aarch64 build may keep failing due to not being in sync with the arch baseimage

Should we just kill it or is it worth the risk for now of it blocking the pipeline?

**Comment by aptalca** [comment]
I'm conflicted. Part of me is curious about how often it would cause issues and how big of an issue.

I guess we can leave it in for now and monitor.

**Comment by thelamer** [comment]
@aptalca given it completely changes the paths and now have many bin symlinks for upgrades needed to drop aarch64 support.

**Pull request merged**
